### ISSUE TITLE
Invalid credentials

### ISSUE THREAD

**Issue by davcho80** [mbillow/ha-chargepoint#4] opened 2022-05-18 01:35 UTC
My chargepoint account is on canada.
I try with user name or email same issues

![image](https://user-images.githubusercontent.com/94725371/168938980-daaea468-b6b5-4c6e-938e-d1b91d1ecbb9.png)

**Comment by mbillow** [comment] 2022-05-27 19:56
Looks like a duplicate of #3. I'll help troubleshoot and see if we can't get this fixed over in that issue. 😄

**Closed by mbillow** 2022-05-27 19:56 UTC
